import properties from './properties';

export const ICON = {
  back: require('assets/icon/icon-back.png'),
  job: require('assets/icon/icon-job.png'),
  degree: require('assets/icon/icon-degree.png'),
  income: require('assets/icon/icon-income.png'),
  asset: require('assets/icon/icon-asset.png'),
  sns: require('assets/icon/icon-sns.png'),
  vehicle: require('assets/icon/icon-vehicle.png'),
  jobNew: require('assets/icon/icon-job-new.png'),
  degreeNew: require('assets/icon/icon-degree-new.png'),
  incomeNew: require('assets/icon/icon-income-new.png'),
  assetNew: require('assets/icon/icon-asset-new.png'),
  snsNew: require('assets/icon/icon-sns-new.png'),
  vehicleNew: require('assets/icon/icon-vehicle-new.png'),
  arrRight: require('assets/icon/icon-arr-right.png'),
  arrRight02: require('assets/icon/icon-arr-right02.png'),
  arrLeft02: require('assets/icon/icon-arr-left02.png'),
  arrBottom: require('assets/icon/icon-arrow-bottom.png'),
  xBtn: require('assets/icon/icon-x.png'),
  xBtn2: require('assets/icon/icon-x2.png'),
  xBtn3: require('assets/icon/icon-x3.png'),
  plus: require('assets/icon/icon-plus.png'),
  plus2: require('assets/icon/icon-plus2.png'),
  distance: require('assets/icon/icon-distance.png'),
  close: require('assets/icon/icon-close.png'),
  like: require('assets/icon/icon-like.png'),
  royalpass: require('assets/icon/icon-royalpass.png'),
  medalAll: require('assets/icon/icon-medal_all.png'),
  tooltip: require('assets/icon/icon-tooltip.png'),
  info: require('assets/icon/icon-info.png'),
  siren: require('assets/icon/icon-siren.png'),
  party: require('assets/icon/icon-party.png'),
  manage: require('assets/icon/icon-manager.png'),
  boy: require('assets/icon/icon-boy.png'),
  girl: require('assets/icon/icon-girl.png'),
  checkOff: require('assets/icon/icon-check-off.png'),
  checkOn: require('assets/icon/icon-check-on.png'),
  star: require('assets/icon/icon-star.png'),
  starHalf: require('assets/icon/icon-star-half.png'),
  starEmpty: require('assets/icon/icon-star-empty.png'),
  starNew: require('assets/icon/icon-star-new.png'),
  starHalfNew: require('assets/icon/icon-star-half-new.png'),
  starEmptyNew: require('assets/icon/icon-star-empty-new.png'),
  starBlack: require('assets/icon/icon-star-black.png'),
  starWhite: require('assets/icon/icon-star-white.png'),
  starYellow: require('assets/icon/icon-star-yellow.png'),
  new: require('assets/icon/icon-new.png'),
  badge: require('assets/icon/icon-badege.png'),
  process: require('assets/icon/icon-process.png'),
  search: require('assets/icon/icon-search.png'),
  pen: require('assets/icon/icon-pen.png'),
  refresh: require('assets/icon/icon-refresh.png'),
  refreshDark: require('assets/icon/icon-refresh-dark.png'),
  penGray: require('assets/icon/icon-pen-gray.png'),
  kakao: require('assets/icon/icon-kakao.png'),
  penCircleGray: require('assets/icon/icon-penCircleGray.png'),
  align: require('assets/icon/icon-align.png'),
  searchGray: require('assets/icon/icon-search-gray.png'),
  searchBlue: require('assets/icon/icon-search-blue.png'),
  searchWhite: require('assets/icon/icon-search-white.png'),
  wait: require('assets/icon/icon-wait.png'),
  pass: require('assets/icon/icon-pass.png'),
  purplePlus: require('assets/icon/icon-purple-plus.png'),
  currency: require('assets/icon/icon-currency.png'),
  ticket: require('assets/icon/icon-ticket.png'),
  currencyTooltip: require('assets/icon/icon-currency-tooltip.png'),
  floatingButton: require('assets/icon/icon-floating-button.png'),
  mileageHistory: require('assets/icon/icon-mileage-history.png'),
  mileageOrder: require('assets/icon/icon-mileage-order.png'),
  roundCrown: require('assets/icon/icon-round-crown.png'),
  delevery: require('assets/icon/icon-delevery.png'),
  crown: require('assets/icon/icon-crown.png'),
  closeBlack: require('assets/icon/icon-close-black.png'),
  backWhite: require('assets/icon/icon-back-white.png'),
  pencil: require('assets/icon/icon-pencil.png'),
  whiteCrown: require('assets/icon/white_crown.png'),
  checkICon: require('assets/icon/checkIcon.png'),
  checkICon02: require('assets/icon/checkIcon02.png'),
  checkICon03: require('assets/icon/checkIcon03.png'),
  marker: require('assets/icon/marker.png'),
  closeCircle: require('assets/icon/closeCircle.png'),
  ticketCircle: require('assets/icon/ticketCircle.png'),
  heartCircle: require('assets/icon/heartCircle.png'),
  heartPurple: require('assets/icon/heartPurple.png'),
  starCircle: require('assets/icon/starCircle.png'),
  asset_on: require('assets/icon/certification/asset_on.png'),
  asset_off: require('assets/icon/certification/asset_off.png'),
  degree_on: require('assets/icon/certification/degree_on.png'),
  degree_off: require('assets/icon/certification/degree_off.png'),
  income_on: require('assets/icon/certification/income_on.png'),
  income_off: require('assets/icon/certification/income_off.png'),
  job_on: require('assets/icon/certification/job_on.png'),
  job_off: require('assets/icon/certification/job_off.png'),
  sns_on: require('assets/icon/certification/sns_on.png'),
  sns_off: require('assets/icon/certification/sns_off.png'),
  vehicle_on: require('assets/icon/certification/vehicle_on.png'),
  vehicle_off: require('assets/icon/certification/vehicle_off.png'),
  limited_on: require('assets/icon/limited_on.png'),
  limited_off_white: require('assets/icon/limited_off_white.png'),
  limited_off_gray: require('assets/icon/limited_off_gray.png'),
  live_on: require('assets/icon/live_on.png'),
  live_off_white: require('assets/icon/live_off_white.png'),
  live_off_gray: require('assets/icon/live_off_gray.png'),
  arrow_right: require('assets/icon/arrow_right.png'),
  plus_primary: require('assets/icon/plus.png'),
  plus_gray: require('assets/icon/plus_gray.png'),
  fashion: require('assets/icon/impression/fashion.png'),
  fond: require('assets/icon/impression/fond.png'),
  smile: require('assets/icon/impression/smile.png'),
  icon_smile: require('assets/icon/icon_smail.png'),
  confirmation: require('assets/icon/confirmation.png'),
  match_succ_icon: require('assets/icon/match_succ_icon.png'),
  passIconNew: require('assets/icon/pass_icon_new.png'),
  royalPassIconNew: require('assets/icon/loyalpass_icon_new.png'),
  passCircle: require('assets/icon/passCircle.png'),
  royalPassCircle: require('assets/icon/royalPassCircle.png'),
  zzimCircle: require('assets/icon/zzimCircle.png'),
  inventoryIcon: require('assets/icon/inventory_icon.png'),
  refuseJobIcon: require('assets/icon/refuse_job_icon.png'),
  refuseAssetIcon: require('assets/icon/refuse_asset_icon.png'),
  refuseEduIcon: require('assets/icon/refuse_edu_icon.png'),
  refuseSnsIcon: require('assets/icon/refuse_sns_icon.png'),
  refuseVehicleIcon: require('assets/icon/refuse_vehicle_icon.png'),
  refuseIncomeIcon: require('assets/icon/refuse_income_icon.png'),
  refuseMaleIcon: require('assets/icon/refuse_male_icon.png'),
  refuseFemaleIcon: require('assets/icon/refuse_female_icon.png'),
  question: require('assets/icon/icon-question.png'),
  level10Icon: require('assets/icon/level_10_icon.png'),
  level15Icon: require('assets/icon/level_15_icon.png'),
  level20Icon: require('assets/icon/level_20_icon.png'),
  level25Icon: require('assets/icon/level_25_icon.png'),
  level30Icon: require('assets/icon/level_30_icon.png'),
  score5Icon: require('assets/icon/score_5_icon.png'),
  score6Icon: require('assets/icon/score_6_icon.png'),
  score7Icon: require('assets/icon/score_7_icon.png'),
  score10Icon: require('assets/icon/score_10_icon.png'),
  scoreDiamondIcon: require('assets/icon/score_diamond_icon.png'),
  scoreKingIcon: require('assets/icon/score_king_icon.png'),
  zzimIcon: require('assets/icon/zzim_icon.png'),
  loveLetterIcon: require('assets/icon/icon-love-letter.png'),
  playIcon: require('assets/icon/play_icon.png'),
  dottedIcon: require('assets/icon/dotted_icon.png'),
  checkOnIcon: require('assets/icon/check_on.png'),
  checkOffIcon: require('assets/icon/check_off.png'),
  loveIcon: require('assets/icon/love_icon.png'),
  boxTipsIcon: require('assets/icon/box_tips_icon.png'),
  giftIcon: require('assets/icon/gift_icon.png'),
  logoTransIcon: require('assets/icon/logo_trans_icon.png'),
  xBlueIcon: require('assets/icon/x_blue_icon.png'),
  xRedIcon: require('assets/icon/x_red_icon.png'),
  saleIcon: require('assets/icon/sale_icon.png'),
  bellIcon: require('assets/icon/bell_icon.png'),
  nextArrowIcon: require('assets/icon/next_arrow_icon.png'),
  celebrityIcon01: require('assets/icon/celebrity_icon01.png'),
  celebrityIcon02: require('assets/icon/celebrity_icon02.png'),
  celebrityIcon03: require('assets/icon/celebrity_icon03.png'),
  celebrityIcon04: require('assets/icon/celebrity_icon04.png'),
  celebrityIcon05: require('assets/icon/celebrity_icon05.png'),
  celebrityIcon06: require('assets/icon/celebrity_icon06.png'),
  secret: require('assets/icon/icon-secret.png'),
  mail: require('assets/icon/icon-mail.png'),
  mailGold: require('assets/icon/icon-mail-gold.png'),
  megaphone: require('assets/icon/icon-megaphone.png'),
  closeLight: require('assets/icon/icon-close-light.png'),
  storyHeart: require('assets/icon/icon-story-heart.png'),
  reply: require('assets/icon/icon-reply.png'),
  clockIcon: require('assets/icon/icon-clock.png'),
  storyPlusIcon: require('assets/icon/icon-story-plus.png'),
  heartOffIcon: require('assets/icon/icon-heart-off.png'),
  heartOnIcon: require('assets/icon/icon-heart-on.png'),
  modfyIcon: require('assets/icon/icon-modfy.png'),
  storyNoIcon: require('assets/icon/icon-story-no.png'),
  betaWhiteIcon: require('assets/icon/icon-beta-white.png'),
  betaBlueIcon: require('assets/icon/icon-beta-blue.png'),
  betaGrayIcon: require('assets/icon/icon-beta-gray.png'),
  talkBalloonIcon: require('assets/icon/icon-talk-balloon.png'),
  talkQuestionIcon: require('assets/icon/icon-talk-question.png'),
  voteIcon: require('assets/icon/icon-vote.png'),
  maleIcon: require('assets/icon/icon-male.png'),
  femaleIcon: require('assets/icon/icon-female.png'),
  confetti: require('assets/icon/confetti.png'),
  storySecretIcon: require('assets/icon/icon-story-secret.png'),
  bookmarkBlack: require('assets/icon/icon-bookmark-black.png'),
  bookmarkPurple: require('assets/icon/icon-bookmark-purple.png'),
  bookmarkWhite: require('assets/icon/icon-bookmark-white.png'),
  murtipleImage: require('assets/icon/icon-murtiple-image.png'),
  speechDotline: require('assets/icon/icon-speech-dotline.png'),
  speechQuestion: require('assets/icon/icon-speech-question.png'),
  storyMale: require('assets/icon/icon-story-male.png'),
  storyFemale: require('assets/icon/icon-story-female.png'),
  padlockMale: require('assets/icon/icon-padlock-male.png'),
  padlockFemale: require('assets/icon/icon-padlock-female.png'),
  pickWhite: require('assets/icon/icon-pick-white.png'),
  pickPurple: require('assets/icon/icon-pick-purple.png'),
  circleX: require('assets/icon/icon-circle-x.png'),
  digitalClock: require('assets/icon/icon-digital-clock.png'),
  authAsset: require('assets/icon/icon-auth-asset.png'),
  authEdu: require('assets/icon/icon-auth-edu.png'),
  authJob: require('assets/icon/icon-auth-job.png'),
  authIncome: require('assets/icon/icon-auth-income.png'),
  authSns: require('assets/icon/icon-auth-sns.png'),
  authVehicle: require('assets/icon/icon-auth-vehicle.png'),
  checkYellow: require('assets/icon/icon-check-yellow.png'),
  checkGold: require('assets/icon/icon-check-gold.png'),
  xYellow: require('assets/icon/icon-x-yellow.png'),
  userAdd: require('assets/icon/icon-user-add.png'),
  userPen: require('assets/icon/icon-user-pen.png'),
  commentYellow: require('assets/icon/icon-comment-yellow.png'),
  commentRed: require('assets/icon/icon-comment-red.png'),
  cloudUpload: require('assets/icon/icon-cloud-upload.png'),
  searchYellow: require('assets/icon/icon-search-yellow.png'),
  bellYellow: require('assets/icon/icon-bell-yellow.png'),
  moneyBill: require('assets/icon/icon-money-bill.png'),
  cardGold: require('assets/icon/icon-card-gold.png'),
  radioYellow: require('assets/icon/icon-radio-yellow.png'),
  squarePen: require('assets/icon/icon-square-pen.png'),
  sirenMark: require('assets/icon/icon-siren-mark.png'),
  hifive: require('assets/icon/icon-hifive.png'),
  heartFace: require('assets/icon/icon-heart-face.png'),
  polygonGreen: require('assets/icon/icon-polygon-green.png'),
  passSquare: require('assets/icon/icon-pass-square.png'),
  circleArrow: require('assets/icon/icon-circle-arrow.png'),
  arrowLeftBrown: require('assets/icon/icon-arrow-left-brown.png'),
  profileYellow: require('assets/icon/icon-profile-yellow.png'),
  profileGray: require('assets/icon/icon-profile-gray.png'),
  bellGold: require('assets/icon/icon-bell-gold.png'),
  bellGray: require('assets/icon/icon-bell-gray.png'),
  cartYellow: require('assets/icon/icon-cart-yellow.png'),
  cartGray: require('assets/icon/icon-cart-gray.png'),
  sparkler: require('assets/icon/icon-sparkler.png'),
  reportBtn: require('assets/icon/icon-report_btn.png'),
  cardCyan: require('assets/icon/icon-card-cyan.png'),
  cardGray: require('assets/icon/icon-card-gray.png'),
  drinkCyan: require('assets/icon/icon-drink-cyan.png'),
  drinkGray: require('assets/icon/icon-drink-gray.png'),
  dotCyan: require('assets/icon/icon-dot-cyan.png'),
  dotGray: require('assets/icon/icon-dot-gray.png'),
  polygonGray: require('assets/icon/icon-polygon-gray.png'),
  megaCubeCyan: require('assets/icon/icon-megacube-cyan.png'),
  cubeCyan: require('assets/icon/icon-cube-cyan.png'),
  cubeYCyan: require('assets/icon/icon-cube-y-cyan.png'),
  menuCyan: require('assets/icon/icon-menu-cyan.png'),
  naverLogo: require('assets/icon/icon-naver-logo.png'),
  circleS: require('assets/icon/icon-circle-s.png'),
  circleA: require('assets/icon/icon-circle-a.png'),
  circleB: require('assets/icon/icon-circle-b.png'),
  circleC: require('assets/icon/icon-circle-c.png'),
  circleD: require('assets/icon/icon-circle-d.png'),
  circleE: require('assets/icon/icon-circle-e.png'),
  circleComplete: require('assets/icon/icon-circle-complete.png'),
  circleUnrank: require('assets/icon/icon-circle-unrank.png'),
  starGray: require('assets/icon/icon-star-gray.png'),
  starCyan: require('assets/icon/icon-star-cyan.png'),
  paiksLogo: require('assets/icon/icon-paiks-logo.png'),
  starbucksLogo: require('assets/icon/icon-starbucks-logo.png'),
  baskinLogo: require('assets/icon/icon-baskin-logo.png'),
  twosomeLogo: require('assets/icon/icon-twosome-logo.png'),
  megaLogo: require('assets/icon/icon-mega-logo.png'),
  daisoLogo: require('assets/icon/icon-daiso-logo.png'),
  cuLogo: require('assets/icon/icon-cu-logo.png'),
  gift: require('assets/icon/icon-gift.png'),
  icChip: require('assets/icon/icon-ic-chip.png'), 
  yBlue: require('assets/icon/icon-y-blue.png'),
  certificate: require('assets/icon/icon-certificate.png'),
  penSquare: require('assets/icon/icon-pen-square.png'),
  circleReward: require('assets/icon/icon-circle-reward.png'),
  chatRed: require('assets/icon/icon-chat-red.png'),
  cardBlack: require('assets/icon/icon-card-black.png'),
  blindDetail: require('assets/icon/icon-blind-detail.png'),
};

export const GIF_IMG = {
  faceScan: require('assets/img/gif/face-scan.gif'),
  loading: require('assets/img/gif/loading.gif'),
  soon: require('assets/img/gif/loading_icon.gif'),
  loadingIcon: require('assets/img/gif/loading_icon_2.gif'),
  loadingNewIcon: require('assets/img/gif/loading_new.gif'),
};

export const IMAGE = {
  logoBanner: require('assets/img/logo_banner.jpg'),
  logoIcon: require('assets/img/logo_icon.png'),
  logoIcon03: require('assets/img/logo_icon03.png'),
  logoStoryTmp: require('assets/img/logo_story_tmp.png'),
  logoStoryBox: require('assets/img/logo_story_box.png'),
  signImg: require('assets/img/sign_img.png'),
  heartImg01: require('assets/img/heart_img.png'),
  heartImg02: require('assets/img/heart_img02.png'),
  logoLeap: require('assets/img/logo_leap.png'),
  logoLeapTmon: require('assets/img/logo_leap_tmon.png'),
  logoLeapTit: require('assets/img/logo_leap_tit.png'),
  logoLeapTit02: require('assets/img/logo_leap_tit02.png'),
  storySecretMale: require('assets/img/story_secret_male.png'),
  storySecretFemale: require('assets/img/story_secret_female.png'),
};

export const PROFILE_IMAGE = {
  manTmp1: require('assets/img/tmp/profile_m_01.jpg'),
  womanTmp1: require('assets/img/tmp/profile_w_01.jpg'),
};

export const GUIDE_IMAGE = {
  daily01Thumnail: require('assets/img/guide/daily_01_thumnail.png'),
  daily01Content: require('assets/img/guide/daily_01_content.png'),
  daily02Content: require('assets/img/guide/daily_02_content.png'),
  daily03Content: require('assets/img/guide/daily_03_content.png'),
  live01Thumnail: require('assets/img/guide/live_01_thumnail.png'),
  live02Thumnail: require('assets/img/guide/live_02_thumnail.png'),
  live03Thumnail: require('assets/img/guide/live_03_thumnail.png'),
  robyThumnail: require('assets/img/guide/roby_thumnail.png'),
  roby01Content: require('assets/img/guide/roby_01_content.png'),
  roby02Content: require('assets/img/guide/roby_02_content.png'),
  roby03Content: require('assets/img/guide/roby_03_content.png'),
  profile01Img: require('assets/img/guide/profile_01_img.png'),
  profile02Img: require('assets/img/guide/profile_02_img.png'),
  profile03Img: require('assets/img/guide/profile_03_img.png'),
  shop01ContentBasic: require('assets/img/guide/shop_01_content_basic.png'),
  shop01ContentBoosting: require('assets/img/guide/shop_01_content_boosting.png'),
  shop01ContentPackage: require('assets/img/guide/shop_01_content_package.png'),
  shop02Content: require('assets/img/guide/shop_02_content.png'),
  shop03Content: require('assets/img/guide/shop_03_content.png'),
  robyProfile01Content: require('assets/img/guide/roby_profile_01_content.png'),
  robyProfile02Content: require('assets/img/guide/roby_profile_02_content.png'),
  robyGrade01Content: require('assets/img/guide/roby_grade_01_content.png'),
  robyGrade02Content: require('assets/img/guide/roby_grade_02_content.png'),
  robyGrade03Content: require('assets/img/guide/roby_grade_03_content.png'),
  storageContent: require('assets/img/guide/storage_content.png'),
};



export function findSourcePath(img_file_path: any) {
  if (img_file_path) {
    if (img_file_path.startsWith('http')) {
      return { uri: img_file_path };
    } else if (img_file_path.startsWith('file:///')) {
      return { uri: img_file_path };
    } else {
      const path = properties.img_domain + img_file_path;
      return { uri: path };
    }
  }
  return img_file_path;
}

export function findSourcePathLocal(img_file_path: any) {
  if (img_file_path) {
    if (img_file_path.startsWith('http')) {
      return { uri: img_file_path };
    } else if (img_file_path.startsWith('file:///')) {
      return { uri: img_file_path };
    } else {
      const path = properties.local_img_domain + img_file_path;
      return { uri: path };
    }
  }
  return img_file_path;
}
